name: Deploy to EC2

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H 44.203.235.117 >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 'echo "SSH connection successful"'

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 << EOF
          # נווט לתיקיית הפרויקט
          cd ~/quick-flight-server

          # עדכן את הפרויקט מה-Repository
          git pull origin master

          # טען את nvm ושימוש בגרסת Node הנכונה
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use node

          # התקן תלותים
          npm install

          # התקן PM2 גלובלי במידה והוא לא מותקן כבר
          npm install -g pm2

          # הפעל מחדש את האפליקציה
          pm2 restart all || pm2 start npm --name "quick-flight-server" -- start
        EOF

    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 "pm2 list"
