name: Deploy to EC2

on:
  push:
    branches:
      - master  # או main, תלוי באיזה ענף ראשי אתה משתמש

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub

    - name: Debug SSH key
      run: |
        if [ -s ~/.ssh/id_rsa ]; then
          echo "SSH key is installed and not empty"
          ls -l ~/.ssh/id_rsa
        else
          echo "SSH key is empty or not installed"
        fi

    - name: Add EC2 to known hosts
      run: ssh-keyscan -H 44.203.235.117 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@44.203.235.117 << EOF
          # Navigate to project directory
          cd ~/quick-flight-server

          # Update the repository
          git pull origin master

          # Load NVM and use the correct Node version
          export NVM_DIR="\$HOME/.nvm"
          [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
          nvm use node

          # Install dependencies
          npm install

          # Install PM2 globally if not already installed
          npm install -g pm2

          # Restart the application
          pm2 restart all || pm2 start npm --name "quick-flight-server" -- start
        EOF

    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        ssh -o StrictHostKeyChecking=no ec2-user@44.203.235.117 "pm2 list"