name: Deploy to EC2

on:
  push:
    branches:
      - master  # או main, תלוי באיזה ענף ראשי אתה משתמש

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    - name: Adding Known Hosts
      run: ssh-keyscan -H 44.203.235.117 >> ~/.ssh/known_hosts
      
    - name: Deploy with rsync
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@44.203.235.117 "
          cd ~/quick-flight-server &&
          git pull origin master &&
          npm install &&
          pm2 restart all
        "