name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 'echo "Connection successful"'

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 "bash -s" <<'EOF'
          cd /home/ec2-user/quick-flight-server || exit 1 # Exit if directory change fails
          git pull origin master || exit 1 # Exit if git pull fails
          npm install || exit 1 # Exit if npm install fails
          npm run build || exit 1 # Add build step if necessary; replace with your actual build command
          pm2 restart all || exit 1 # Exit if pm2 restart fails
          EOF