name: Deploy to EC2

on:
  push:
    branches:
      - master  # או main, תלוי באיזה ענף ראשי אתה משתמש

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        
    - name: Debug SSH key
      run: |
        if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
          echo "EC2_SSH_KEY is empty"
        else
          echo "EC2_SSH_KEY is set and not empty"
        fi

    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 44.203.235.117 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@44.203.235.117 << EOF
          # Navigate to project directory
          cd ~/quick-flight-server

          # Update the repository
          git pull origin master

          # Load NVM and use the correct Node version
          export NVM_DIR="\$HOME/.nvm"
          [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
          nvm use node

          # Install dependencies
          npm install

          # Install PM2 globally if not already installed
          npm install -g pm2

          # Restart the application
          pm2 restart all || pm2 start npm --name "quick-flight-server" -- start
        EOF