name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          set -x # Print executed commands
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ls -la /home/runner/.ssh # List files in .ssh directory for verification

      - name: Test SSH connection
        run: |
          set -x
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 'echo "Connection successful"' || exit 1

      - name: Deploy to EC2
        run: |
          set -x
          echo "Current working directory: $(pwd)" 
          echo "Node.js version: $(node -v)" 
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 "bash -s" <<'EOF'
          cd /home/ec2-user/quick-flight-server || exit 1
          echo "Deployment directory: $(pwd)"
          git pull origin master || exit 1
          npm install || exit 1
          pm2 restart all || exit 1
          EOF