name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 'echo "Connection successful"'

      - name: Deploy to EC2
        run: |
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@44.203.235.117 <<EOF
          cd /home/ec2-user/quick-flight-server &&
          git pull origin master &&
          npm install &&
          pm2 restart all
          EOF
